Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
layer_from_list.df.plot(ax=demo_area.df.plot(), color="orange")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/geopandas/plotting.py[0m in [0;36m_plot_polygon_collection[0;34m(ax, geoms, values, color, cmap, vmin, vmax, **kwargs)[0m
[1;32m    119[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 120[0;31m         [0;32mfrom[0m [0mdescartes[0m[0;34m.[0m[0mpatch[0m [0;32mimport[0m [0mPolygonPatch[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    121[0m     [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'descartes'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-7-0ec2cd1fc7d5>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mlayer_from_list[0m[0;34m.[0m[0mdf[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0max[0m[0;34m=[0m[0mdemo_area[0m[0;34m.[0m[0mdf[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m"orange"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/geopandas/geodataframe.py[0m in [0;36mplot[0;34m(self, *args, **kwargs)[0m
[1;32m    919[0m         [0;32mfrom[0m [0mthere[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    920[0m         """
[0;32m--> 921[0;31m         [0;32mreturn[0m [0mplot_dataframe[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    922[0m [0;34m[0m[0m
[1;32m    923[0m     [0mplot[0m[0;34m.[0m[0m__doc__[0m [0;34m=[0m [0mplot_dataframe[0m[0;34m.[0m[0m__doc__[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/geopandas/plotting.py[0m in [0;36mplot_dataframe[0;34m(df, column, cmap, color, ax, cax, categorical, legend, scheme, k, vmin, vmax, markersize, figsize, legend_kwds, categories, classification_kwds, missing_kwds, aspect, **style_kwds)[0m
[1;32m    613[0m [0;34m[0m[0m
[1;32m    614[0m     [0;32mif[0m [0mcolumn[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 615[0;31m         return plot_series(
[0m[1;32m    616[0m             [0mdf[0m[0;34m.[0m[0mgeometry[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    617[0m             [0mcmap[0m[0;34m=[0m[0mcmap[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/geopandas/plotting.py[0m in [0;36mplot_series[0;34m(s, cmap, color, ax, figsize, aspect, **style_kwds)[0m
[1;32m    411[0m [0;34m[0m[0m
[1;32m    412[0m         [0mvalues_[0m [0;34m=[0m [0mvalues[0m[0;34m[[0m[0mpoly_idx[0m[0;34m][0m [0;32mif[0m [0mcmap[0m [0;32melse[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 413[0;31m         _plot_polygon_collection(
[0m[1;32m    414[0m             [0max[0m[0;34m,[0m [0mpolys[0m[0;34m,[0m [0mvalues_[0m[0;34m,[0m [0mfacecolor[0m[0;34m=[0m[0mfacecolor[0m[0;34m,[0m [0mcmap[0m[0;34m=[0m[0mcmap[0m[0;34m,[0m [0;34m**[0m[0mstyle_kwds[0m[0;34m[0m[0;34m[0m[0m
[1;32m    415[0m         )

[0;32m/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/geopandas/plotting.py[0m in [0;36m_plot_polygon_collection[0;34m(ax, geoms, values, color, cmap, vmin, vmax, **kwargs)[0m
[1;32m    120[0m         [0;32mfrom[0m [0mdescartes[0m[0;34m.[0m[0mpatch[0m [0;32mimport[0m [0mPolygonPatch[0m[0;34m[0m[0;34m[0m[0m
[1;32m    121[0m     [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 122[0;31m         raise ImportError(
[0m[1;32m    123[0m             [0;34m"The descartes package is required for plotting polygons in geopandas. "[0m[0;34m[0m[0;34m[0m[0m
[1;32m    124[0m             [0;34m"You can install it using 'conda install -c conda-forge descartes' or "[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: The descartes package is required for plotting polygons in geopandas. You can install it using 'conda install -c conda-forge descartes' or 'pip install descartes'.
ImportError: The descartes package is required for plotting polygons in geopandas. You can install it using 'conda install -c conda-forge descartes' or 'pip install descartes'.

